SCHEMA = """
CREATE TABLE IF NOT EXISTS woodcfg (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    guild_id INTEGER NOT NULL,
    tplaylist TEXT DEFAULT "PLb1JKHu_D4MTBXu-8MCFBJ855RpoUuYTf",
    koko_role INTEGER
)
"""
