SCHEMA = """
CREATE TABLE IF NOT EXISTS woodcfg (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    guild_id INTEGER NOT NULL UNIQUE,
    threshold INTEGER DEFAULT 5,
    channel_id INTEGER
)
"""
